minio/minio-py

README.md
minio/generators.py
minio/helpers.py
minio/minio.py
minio/parsers.py
minio/signer.py
tests/unit/sign_test.py

- region is automatically calculated and cached.
- all requests to Amazon S3 with bucket names are virtualized.
- Fix a bug in ListIncompleteUploads().
Fixes #286

minio-py: Full API revamp - default to virtual bucket style for python.

---

minio/api.py
minio/io.py
minio/parsers.py
minio/xml_requests.py
tests/unit/get_object_test.py
tests/unit/stat_object_test.py

io: Implement HTTPReadSeeker and use it.

---

minio/api.py
minio/error.py
minio/generators.py
minio/helpers.py
minio/io.py
minio/parsers.py

parse_error has been converged into ResponseError.
ResponseError constructs necessary Exceptions for
different methods 'HEAD', 'DELETE', 'GET', 'PUT' and 'POST'
by providing self contained functions for reach.

minio-py: Cleanup error handling - provide it individually.

---

examples/bucket_exists.py
examples/get_bucket_acl.py
examples/get_object.py
examples/get_partial_object.py
examples/list_buckets.py
examples/list_incomplete_uploads.py
examples/list_objects.py
examples/make_bucket.py
examples/presigned_get_object.py
examples/presigned_post_policy.py
examples/presigned_put_object.py
examples/put_object.py
examples/remove_bucket.py
examples/remove_incomplete_upload.py
examples/remove_object.py
examples/set_bucket_acl.py
examples/stat_object.py
minio/api.py
minio/post_policy.py

postPolicy: Implement content length range for post policy.

---

README.rst
examples/presigned_post_policy.py
minio/api.py
minio/error.py
minio/generators.py
minio/helpers.py
minio/io.py
minio/post_policy.py
minio/signer.py
minio/xml_marshal.py

- split _do_put_object into _do_put_object and _do_put_multipart_object.
- Fix couple of bugs in streaming upload.

api: Cleanup another round

---

examples/list_incomplete_uploads.py
examples/list_objects.py
examples/presigned_get_object.py
examples/presigned_post_policy.py
examples/presigned_put_object.py
minio/api.py
minio/bucket_acl.py
minio/definitions.py
minio/error.py
minio/generators.py
minio/helpers.py
minio/io.py
minio/parsers.py
minio/post_policy.py
minio/signer.py
minio/xml_marshal.py
tests/unit/list_uploaded_parts_test.py

pep8: All pep8 fixes.

---

minio/api.py
minio/helpers.py
minio/post_policy.py
minio/xml_marshal.py
tests/functional/tests.py
tests/unit/bucket_exist_test.py
tests/unit/generate_xml_test.py
tests/unit/get_bucket_acl_test.py
tests/unit/get_object_test.py
tests/unit/helpers.py
tests/unit/list_buckets_test.py
tests/unit/list_incomplete_uploads_test.py
tests/unit/list_objects_test.py
tests/unit/list_uploaded_parts_test.py
tests/unit/make_bucket_test.py
tests/unit/minio_test.py
tests/unit/presigned_get_object_test.py
tests/unit/presigned_put_object_test.py
tests/unit/remove_bucket_test.py
tests/unit/remove_object_test.py
tests/unit/set_bucket_acl_test.py
tests/unit/stat_object_test.py

- Cleanup and handle the new conditions.
- Add more tests.

rewrite: Rewrite unit tests.

---

minio/api.py
minio/definitions.py
minio/parsers.py
tests/functional/tests.py

Additionally this patch also removes region from cache upon any error.

fput_object: Complete multipart upload result should be parsed.

---

.travis.yml
minio/api.py
minio/helpers.py
tests/functional/tests.py

Also print response body during error xml.

trace: Redact signature header value from being printed in trace logs.

---

minio/api.py
tests/unit/bucket_exist_test.py

return false if NoSuchBucket error occurs

---

minio/api.py
minio/compat.py

`xrange` is not available in Py3

---

minio/api.py

`range(1,N)` function returns `[1, 2 ,..., N-1]`. So the line `if part_number == total_parts_count` never evaluates to `True`. It's always `False`. I tried changing it to `if part_number == total_parts_count - 1`, but it did not work. I changed the range to `range(1, N+1)`. It seems to be working for me.  ***BUT***, this might not be an Ideal fix. Just sending a PR to whatever scratched my itch.

Count till Nth than before Nth

---

README.rst

Previously markdown was copied instead of restructured text format. This patch fixes this.

doc: README.rst updated with proper formatting.

---

README.md

Fixed typo & added 
1. API reference for ``get_partial_object``
2. remove_incomplete_upload.py example

Fixed typo & added get_partial_object

---

API.md

changes to bring content in sync with docs.minio.io

doc:API.md/changes to bring content in sync with docs.minio.io

---

docs/API.md

Fixes this bug : https://github.com/minio/cookbook/issues/31

doc: Fix Anchor Tags

---

minio/api.py
minio/parsers.py

Code: Spelling corrections in files listed.

---

docs/API.md
examples/get_object.py

Fixes https://github.com/minio/minio-py/issues/402

Fix examples to indicate that we should be using streams.

---

docs/API.md
minio/api.py
minio/copy_conditions.py
tests/functional/tests.py
tests/unit/copy_object_test.py

Improve copy_object API, add more tests.

---

docs/API.md
minio/helpers.py
tests/unit/get_s3_endpoint_test.py

This should fix #396 
#hacktoberfest

Add support for cn-north-1 endpoint (#396)

---

minio/api.py
minio/signer.py

This was experienced and reported by @elcolie.

Fix a bug in presigned URL, resulted in invalid payload.

---

minio/api.py

This fix the following error:
error while uploading: ResponseError: code: AuthorizationHeaderMalformed, message: The authorization header is malformed; the region 'EU' is wrong; expecting 'eu-west-1', bucket_name: XXXXXXX, object_name: haproxy/haproxy.internal.cfg, request_id: 03B8839191B53B93, host_id: NcXHgl8oBI4EaNcQh9unq0xqoUwT23xOSLDYqq6yCPZLG+Z4vR7Pmxlyvbse4xlFGdcaWF7r488=, region:

fixed EU location check

---

minio/api.py

Thanks to @dcharbonnier to providing this snippet.
This patch also adds getBucketLocation() to have http trace.

Add proper retries for all our requests.

---

minio/parsers.py

parsers: Expect empty ETag in objects list

---

setup.py

fix(urllib3): add minimum required version

---

setup.py

certifi and urllib3 should be latest always, for security.

ensure that install is latest for deps

---

minio/policy.py

Make resource compatible with new policy

---

minio/policy.py
tests/functional/tests.py

Fix set_bucket_policy crash in bucket_resource handling.

---

docs/API.md
minio/api.py

Add timeout for Minio constructor.

---

minio/fold_case_dict.py

FoldCaseDict should extend python dict

---

docs/API.md
examples/listen_notification.py
minio/api.py
minio/signer.py
tests/unit/remove_objects_test.py
tests/unit/sign_test.py

Also fixes wrong signature query param generation, sorting was
done wrong parsed_url.url already gives url in a parsed form.
Fixes #493

api: ListenBucketNotification now supports s3:ObjectAccessed:*

---

minio/api.py

Use md5_hex for parts' md5sum

---

tests/functional/tests.py

tests: put_object a big file to cover more code

---

minio/api.py

multipart: Disable resuming incomplete uploads

---

minio/api.py
minio/helpers.py
tests/functional/tests.py

- content-md5 is calculated and set if HTTPS server
endpoint is used.
- content_sha256 is calculated and set if HTTP server
endpoint is used.
Fixes #511

api: put_object shouldn't calculate md5sum always.

---

tests/functional/tests.py

Split tests into functions

---

minio/api.py
minio/compat.py
minio/helpers.py
minio/thread_pool.py

Fixes #503 
Based on the first attempt here https://github.com/minio/minio-py/pull/536

Parallel upload of object parts

---

docs/API.md

Updated example of presigned_post_policy to include the set_content_type method

Updated example to include the set_content_type method

---

tests/functional/tests.py

Updates minio-py to output new mint log format

---

tests/functional/tests.py

Introduces log output class

---

minio/api.py

Presigned delete url

---

tests/functional/tests.py

1. Add prefix to the bucket name
2. Convert the duration to milliseconds
3. Remove description field
4. Remove entries that contain null in json
Fixes #576, #583

Fix minor bugs in logging format

---

tests/functional/tests.py

We need this temporary behavior is Mint can succeed. This will be revert
once bucket policy will be implemented in all gateways.
Fixes #579

tests: Return NA when APINotImplemented for bucket policy

---

minio/policy.py
tests/functional/tests.py

Fixes gcs/azure bucket policy test issues

---

README.md

Update readme for minio-py installation using pip3

---

minio/helpers.py

Strip port 80/443 only for the corresponding protocol, http/https

---

docs/API.md

Adds some missing defaults and params

---

docs/zh_CN/API.md

fix issue #645.
Chinese version of API doc needs to be updated to reflect set/getBucketPolicy fix (PR#639).

fix issue #645.

---

tests/functional/tests.py

test_thread_safe creates some objects using get_object primitive but
download only one object. The other get_object instances that haven't been
read yet will hold a read lock in Minio server. In consequence, the next
call to remove object primitive will stale since it requires full lock.
Without this PR, test_thread_safe can get stalled in some machines.

tests: Fix test_thread_safe behavior

---

docs/API.md
tests/functional/tests.py

Custom metadata doc and test changes

---

minio/parsers.py

Do not urldecode Key from list_objects response

---

minio/api.py

Do not add metadata headers during completeMultipart

---

docs/API.md

fix documentation for list_objects and list_objects_v2

---

minio/api.py
tests/functional/tests.py

- Fixes #696 
- Added functional test

Handle empty XML response in get_bucket_notification

---

docs/API.md
docs/zh_CN/API.md
examples/copy_object_with_metadata.py
minio/api.py
tests/functional/tests.py

Metadata support for copy_object

---

minio/helpers.py
tests/unit/header_value_test.py

Fix #738 allow copy_object to set content-type

---

setup.py

Only needed for python2
https://pypi.org/project/future/

Remove future depdency for python3

---

tests/functional/tests.py

Fixes https://github.com/minio/minio/issues/8092

Increase presigned timeouts for functional tests

---

.github/workflows/pythonpackage-linux.yml
.github/workflows/pythonpackage-windows.yml
minio/helpers.py

Fixed an issue where == should be used instead of "is" for python 3.8
closes #846

python 3.8 compatibility

---

minio/helpers.py

Fix deprecation warnings due to invalid escape sequences.

---

.gitignore
README.md
docs/API.md
examples/get_bucket_encryption.py
examples/remove_bucket_encryption.py
examples/set_bucket_encryption.py
minio/api.py
minio/xml_marshal.py

This PR brings bucket encryption control thru Python SDK apis;
- put_bucket_encryption
- get_bucket_encryption
- delete_bucket_encryption

Support to put/get/delete default encryption config apis on a bucket

---

.github/workflows/pythonpackage-linux.yml
.github/workflows/pythonpackage-windows.yml

using the fix proposed in https://github.com/actions/checkout/issues/23

fix github actions error while checking out

---

Makefile
minio/api.py
minio/error.py

fix pylint errors in error.py

---

.github/workflows/pythonpackage-linux.yml
.github/workflows/pythonpackage-windows.yml
docs/API.md
examples/select_object_content.py
minio/compat.py
minio/signer.py
tests/unit/minio_test.py
tests/unit/sign_test.py

update tests as well and also update
select object example with new API
changes.

fix presigned_url generation issue

---

docs/API.md
minio/api.py

Tiny edits for consistency and a fix for set_bucket_policy

fix typos in docstring and API guide

---

.github/workflows/pythonpackage-linux.yml
.github/workflows/pythonpackage-windows.yml
Makefile
setup.py

Remove configparser as dependency

---

minio/tagging.py

fix XML construction in Tagging

---

.gitignore
minio/api.py
minio/commonconfig.py

I've just decided to start with something simple to get better acquainted with the codebase. The PR simply addresses the warnings that PyCharm linter is complaining about

fix docstring and error handling in _validate_size()

---

minio/api.py

fix Tagging.tags property usage

---

minio/helpers.py

fix Retention properties usage

---

minio/api.py

fix getbytes() usage in make_bucket() API

---

docs/API.md
minio/api.py
minio/helpers.py

fix data argument description of put_object() API

---

minio/helpers.py

Fix divided by zero error at part info computation.

---

minio/helpers.py

Optimize logic of read_part_data()

---

minio/api.py

fix user metadata query parameter in list_objects()

---

minio/lifecycleconfig.py

Add non-empty filter rule check in Lifecycle configuration.

---

minio/select.py

Add compression type in XML of Input Serialization

---

docs/API.md
examples/listen_bucket_notification.py
minio/__init__.py
minio/api.py
minio/datatypes.py

Fixes #1117
Signed-off-by: Bala.FA <bala.gluster@gmail.com>

listen_bucket_notification(): return EventIterable object as controlled iterator.

---

tests/functional/tests.py

Fixes #1120
Signed-off-by: Bala.FA <bala.gluster@gmail.com>

fix pylint errors

---

minio/api.py
minio/credentials/providers.py

Raise ValueError instead of returning in ChainedProvider

---

minio/replicationconfig.py

fix: do not enforce role value for replicationConfig

---

minio/error.py

Add __reduce__() method to errors for pickle compatible.

---

minio/deleteobjects.py
minio/lifecycleconfig.py
tests/unit/remove_objects_test.py

fix converting boolean value to XML boolean.

---

minio/api.py

fix make version-id dictionary instead of set

---

minio/api.py
minio/error.py

Handle 304 status code properly

---

minio/helpers.py

should be maximum and not minimum?

correct ValueError when part_size > MAX_PART_SIZE

---

minio/api.py

fget_object(): remove resume support.

---

minio/lifecycleconfig.py

fix lifecycle config rule validation

---

minio/lifecycleconfig.py

error out if lifecycle rule has null filter

---

minio/datatypes.py

EventIterable: Reconnect on closed response.

---

docs/API.md

Fix Document on Website
https://docs.min.io/docs/python-client-api-reference.html#get_presigned_url
Signed-off-by: ZhengSheng0524 <j13tw@yahoo.com.tw>

fix documentation display composing

---

minio/api.py

add progressbar at fget_object

fget_object(): add progress support

---

README.md
README_zh_CN.md
docs/API.md
docs/zh_CN/API.md

Updates links to the docs throughout the repo to point to the new doc site URLs.

Updating documentation links to new URLs

---

minio/api.py

fget_object(): create tmp_file_path string generically

---

docs/API.md
examples/upload_snowball_objects.py
minio/api.py
minio/commonconfig.py
minio/time.py

Add upload_snowball_objects() API

---

tests/functional/tests.py

checks: ignore broad-exception-raised pylint error

---

examples/upload_snowball_objects.py
minio/api.py

upload_snowball_object(): seek stream to 0 before upload

---

minio/datatypes.py

This reverts commit f764d45fbcb6ac97882851961e5d58afe86655d8.

Revert "list_objecst: fix parsing user metadata as per MinIO server (#1240)"

---

minio/minioadmin.py

ran `make check` and it looks like it is good to go, however, I'm still not sure if credentials should be type Provider or not? Open to feedback to improve this!

Add type hints for MinioAdmin class

---

minio/__init__.py
minio/api.py

This pull request fixes the issue mentioned in #1332

fix part size value appropriately in upload_snowball_objects() API

---

minio/helpers.py

Ignore Amazon EC2 public domain as AWS S3 domain

---

minio/minioadmin.py

Added the missing functions to manage service accounts with this library.
This closes #1307.

MinioAdmin: Add {add,update,delete,list,get}_service_account APIs

---

minio/crypto.py

Resolves https://github.com/minio/minio-py/issues/1408

fix: missing f-string for a ValueError

---

minio/signer.py
tests/functional/tests.py

SignV4: trim leading/trailing spaces in header value

---

minio/api.py

Pass request_headers to stat_object API from fget_object API

---

.github/workflows/ci.yml
minio/credentials/providers.py

IamAwsProvider: fix url with role name

---

minio/datatypes.py

fix ETag parsing in CompleteMultipartUploadResult
