minio/minio-py

- README.md
- examples/presigned_get_object.py
- examples/presigned_put_object.py
- minio/definitions.py
- minio/generators.py
- minio/helpers.py
- minio/minio.py
- minio/parsers.py
- tests/unit/bucket_exist_test.py
- tests/unit/remove_bucket_test.py
- tests/unit/remove_object_test.py
- tests/unit/set_bucket_acl_test.py
- tests/unit/stat_object_test.py
- presigned get/put request now always take native type for timedelta.
- presigned post policy shouldn't have policy as optional argument.
- is_valid_bucket_name regex should verify for Amazon S3 compatible
bucket names, i.e bucket names can be capitalized and can contain numbers.
- improve upon documentation.
Fixes #296
> minio-py: All functions should take native types if possible.

- minio/api.py
We do not need to default to 'us-east-1' for non-S3 endpoints.
> get_bucket_location: Do not default to 'us-east-1' for non S3 endpoints.

- API.md
- examples/presigned_post_policy.py
- minio/api.py
The reason to do this is because bucket names can be in
various different regions and for users it becomes convenient
if we return back the proper endpoint which can be safely used
without worrying about virtual host style or path style.
We have enough information to provide a proper URL, this is also
consistent with other Presigned operations as it would be an
expected behavior.
> api: change presigned_post_policy to return back proper URL.

- README.md
- README.rst
- docs/API.md
- examples/get_bucket_policy.py
- examples/set_bucket_policy.py
- minio/api.py
- minio/policy.py
> api: add get_bucket_policy and set_bucket_policy.

- docs/API.md
- examples/set_bucket_policy.py
- minio/api.py
- minio/policy.py
- tests/functional/tests.py
Also fix the API set_bucket_policy() should take input
policy as the last option and API should be consistent
with other languages.
This patch also adds a functional test case.
Fixes #399
> api: Fix python3 compatibility issue by using compat values.

- docs/API.md
Python's io.IOBase does not implement the read() method, but
io.RawIOBase does (in both major Python versions 2.7 and 3.5).
Technically, we only need an object that implements a `read()` method that takes an integer. We make no use of any of the other methods.
> Fix doc for `put_object`

- minio/signer.py
`bytes` is not supported in 2.7
`str.decode` is not supported in 3.5
However,
`b'UNSIGNED-PAYLOAD'` value has type `str` in python 2.7 and `bytes` and python 3.5. 
That way, it will be  possible to decode that value using the same code in both 2.7 and 3.x
Fixes #418 and #417
> More portable way of decoding 'UNSIGNED-PAYLOAD' value to satisfy both python 2.x and 3.x

- minio/signer.py
It was introduced in commit id 31e8a35b18436267b0582cfb9e3f16f8ed65017a - once this was found (with git bisect), the fix was easy to figure out.
`_get_bucket_region()` was failing in Python 3 with signature mismatch
error.
Short program that demonstrates the issue:
```py
from minio import Minio
from minio.error import ResponseError
from sys import stdout
s3Client = Minio(
'localhost:9000',
access_key='minio',
secret_key='minio123',
secure=False,
)
s3Client.trace_on(stdout)
objects = s3Client.list_objects('aditya', recursive=True)
for c, obj in enumerate(objects):
print(obj)
if c > 10:
break
```
Generates:
```sh
Traceback (most recent call last):
File "../minio-test.py", line 21, in <module>
for c, obj in enumerate(objects):
File "/home/aditya/Code/minio-code/python/venv/lib/python3.5/site- …
```
> Fix sign v4 breakage in Python 3

- docs/API.md
- examples/removing_objects.py
- minio/api.py
- minio/error.py
- minio/parsers.py
- minio/xml_marshal.py
- tests/functional/tests.py
- tests/unit/remove_objects_test.py
* Adds new `remove_objects` method that performs multi-object delete.
* Adds unit tests.
* Adds functional tests.
* Adds documentation and example.
> Add Multi-Object Delete API support (Fixes #413)

- README.md
- docs/API.md
- examples/remove_object.py
- examples/remove_objects.py
- minio/api.py
- minio/parsers.py
- tests/functional/tests.py
- tests/unit/list_objects_v2_test.py
* Adds new `list_objects_v2` function that uses the V2 List Objects API
* Adds unit test and functional test.
* Adds docs and example.
This patch also incorporates a better namespace aware XML parsing style. The existing `list_objects` function should also be separately improved to use this style.
> Add List Objects V2 API (Fixes #376)

- docs/API.md
- minio/api.py
- minio/signer.py
- tests/unit/presigned_get_object_test.py
This allows users to specify additional querystring params supported by S3 API such as
`response-content-type` and `response-content-disposition`.
This was done following discussion on Gitter with @harshavardhana and @balamurugana
> Add support for `response_headers` argument on `presigned_get_object`

- minio/api.py
- minio/helpers.py
- minio/signer.py
get_sha256(): Now accepts either `bytes` or `str` type (i.e. unicode)
and always returns hexadecimal encoded digest as a `str` (unicode)
type in both Python 3.x and Python 2.x. This greatly simplifies code
related to sha256 hash usage.
Towards resolving #437.
This refactor is to improve the interaction of string types in the library and improve the code quality.
> Part 1 in Strings/Bytes refactor:

- minio/parsers.py
Adds new S3 aware parser helper class S3Element:
- Captures commonly performed S3 related parsing actions
- Is namespace aware
- Eliminate usage of large repetitive constants
- Easy to use and has lead to significant simplication of code
Fixes #432.
> XML Parsing refactor:

- minio/api.py
- minio/helpers.py
- minio/post_policy.py
- minio/signer.py
- Modify `get_md5` to `get_md5_base64digest`. This function now works
for both str and bytes type inputs and returns str
type (i.e. unicode string). It performs base64 encoding. This
simplifies md5 related hashing code. It has the same behaviour in
both Py2 and Py3 now.
- Add new Hasher class that provides `md5` an `sha256` hashers similar
to hashlib, but always returns unicode string encoded hex/base64
digests.
Towards resolving #437
> Part 2 of Strings/Bytes Refactor:

- minio/policy.py
minio is returning resource as a list
```
{"Version":"2012-10-17","Statement":[{"Action":["s3:GetBucketLocation","s3:ListBucketMultipartUploads"],"Effect":"Allow","Principal":{"AWS":["*"]},"Resource":["arn:aws:s3:::mycroft-public"],"Sid":""},{"Action":["s3:GetBucketLocation"],"Effect":"Allow","Principal":{"AWS":["*"]},"Resource":["arn:aws:s3:::mycroft-public"],"Sid":""},{"Action":["s3:AbortMultipartUpload","s3:DeleteObject","s3:ListMultipartUploadParts","s3:PutObject"],"Effect":"Allow","Principal":{"AWS":["*"]},"Resource":["arn:aws:s3:::mycroft-public/*"],"Sid":""},{"Action":["s3:GetBucketLocation"],"Effect":"Allow","Principal":{"AWS":"*"},"Resource":["arn:aws:s3:::mycroft-public"],"Sid":""},{"Action":["s3:ListBucket"],"Effect":"Allow","Principal":{"AWS":"*"},"Resource":["arn:aws:s3:::mycr …
```
> Update resource as per new policy

- docs/API.md
It seems that the Minio Server expects the response_headers in lowercase.  When using the camel case version of the header names, the server does not include the headers. Thus, I modified the docs according to this convention.
> Changed response_header to lowercase in docs

- minio/api.py
- tests/unit/minio_mocks.py
For most API requests (except GET object), the response is not large
and can be loaded into memory. Preloading content makes re-use of
connections automatic - the connection is returned to the connection
pool before the response object is returned to the caller of
urlopen().
The only exception, GET object, uses preload_content=False - this
allows the caller to incrementally process the response - but as a
caveat would need to release the connection manually by calling
`release_conn()` on the returned object. Docstrings have been
updated to reflect this.
Fixes #458.
> Make HTTP(S) responses always preload content by default:

- docs/API.md
- minio/api.py
Add region= option to our API constructor. This option
is added to avoid making calls to server when an
application written using `minio-py` is only meant
to generate presigned URLs which is a quite common use
case.
Setting this option - overrides any future region
changes and makes the API more stricter. For example
if you are going to use your initialized client
against a bucket which exists in a different region
all API operations would fail.
> Allow bucket region cache to be overriden.

- minio/api.py
- minio/policy.py
- tests/unit/get_bucket_policy_test.py
1. `response.read()` in `_get_bucket_policy` is incorrect. We should be using `response.data` instead.
2. ~`Resource` is a list of the form `["arn:aws:s3:::test-bucket"]`. Thus using 0th index instead.~
3. Added python 2/3 compatible code.
4. Added tests.
5. Fix bug in `_get_permissions`
> get_bucket_policy is broken

- minio/api.py
- minio/policy.py
This patch fixes a bug in
- get_bucket_policy when there is no policy
return policy.NONE
- set_bucket_policy should delete policy
properly when asked for Policy.NONE
> policy: Should treat policy.NONE by removing statements.

- docs/API.md
- minio/api.py
Additionally also return the stat info of the original
object for fget_object.
Fixes #480
Fixes #481
> Return consistent outputs for put_object/fput_object

- docs/API.md
- minio/api.py
- minio/fold_case_dict.py
- minio/helpers.py
- minio/signer.py
- tests/functional/tests.py
- tests/unit/minio_mocks.py
- tests/unit/sign_test.py
This is implemented since we have already implemented
PutObjectWithMetadata() in minio-go. So following the
logic here.
This adds support to be able to specify `x-amz-storage-class` etc.
Fixes #482
> Add support for additional metadata headers.

- minio/api.py
Added a parameter to the Minio class initialization method that allows users to provide their own certificate bundle. One example use case scenario would be if a user wanted to provide a self signed certificate to use with their Minio object. If the user doesn't provide a certificate bundle themselves, Minio will default to using Certifi's (certifi.where()) certificate bundle.
> Custom certificate bundles

- minio/api.py
- tests/functional/tests.py
- tests/unit/list_incomplete_uploads_test.py
Setting query params in the following manner fails to
generate the proper query params used for validating
signature.
```
query = {'test': None}
```
Generates a url of form `/?test` doesn't work.
```
query = {'test': ''}
```
Generates a url of form `/?test=`  works.
> signV4: Fix signature issue while doing multipart upload.

- docs/API.md
- minio/api.py
- minio/definitions.py
- tests/functional/tests.py
We allow custom metadata to be set
in fput_object(). So we shall properly
return custom metadata back as requested
by the caller.
Fixes https://github.com/minio/minio/issues/4136
> api: Return custom metadata in stat_object.

- docs/API.md
I had written something thinking it should be 
```
buckets = client.list_buckets()
bucket_set = set([bucket.bucket_name for bucket in buckets])
```
but I actually had to write
```
buckets = client.list_buckets()
bucket_set = set([bucket.name for bucket in buckets])
```
> correct bucket_name to bucket.name

- examples/presigned_post_policy.py
Indentation was off in the curl command - it ends up appending file to every field in the form.
> Example: Fix curl command for presigned post

- docs/API.md
- examples/put_and_get_encrypted_object.py
- minio/api.py
- tests/functional/tests.py
Regard to this issue: https://github.com/minio/minio-py/issues/521 I want to add support for additional headers in `get` methods.
> Add metadata to get, fget and get_partial methods

- minio/compat.py
- tests/functional/tests.py
Listening to bucket events is not working properly for Windows
since pathname2url was trying to encode s3:ObjectCreated:* which
is not a valid path under Windows. Correct the behavior by using
urllib.quote() and unquote() instead.
Fix #523 
Function and unit tests are passing.
> fix: Use urllib.quote() instead of pathname2url()

- minio/helpers.py
curl & browsers strip port 80 and 443 from host header when a user tries
to open a presigned urls, the thing that leads to a signature mismatch error.
This PR strips port 80/443 by default.
Fixes #527
> signv4: Strip port 80 & 443 from url

- minio/api.py
- minio/helpers.py
It would be little easier to use hex directly to express
a part's md5 or sha256 sum instead of hash interface. Convert
hex to base64 whenever we need that.
> Use hex instead of hash interface in partMetadata

- tests/functional/tests.py
dict.has_key() is not supported in Python 3, replace
it with `if elem in dict:`
Fixes #533
> tests: Fix functional tests for Python 3

- .travis.yml
- appveyor.yml
- minio/api.py
- minio/compat.py
- minio/helpers.py
- minio/signer.py
- tests/functional/tests.py
- tests/unit/sign_test.py
python2.7 lacks proper unicode support, so we need
a proper wrapper function for url encoding. With
this the url and query encodings works for all
unicode characters.
Fixes #529
> url: resource and query encoding should support unicode

- tests/functional_test.sh
- tests/unit_test.sh
Fixes #532 
This is just a convenience script for developers to ensure that unit tests and functional tests pass with both python2 and python3
Commit  	2c2046e is identical to fix by @vadmeste for #533
> Run tests with both python2 and python3

- minio/api.py
Fixes #558 
get_bucket_policy  function crashes with TypeError when azure gateway returns null statements in Policy
{"Version":"2012-10-17","Statement":null}. Check value returned before appending to statements list.
> Fix get_bucket_policy crash for TypeError

- tests/functional/tests.py
Path append was accidentally merged in the code, it was only helping me
to test locally.
> tests: Remove useless path append

- docs/API.md
- minio/api.py
stat_object was returning seconds in float in last_modified field,
replace it by a time.time object.
Fixes #557
> API: stat_object returns time.time instead of secs

- minio/api.py
Fixes #553.
When list_buckets call is invoked without credentials on s3.amazonaws.com , AWS redirects to its home page and returns RC 200 with html content instead of Xml with ListBucketsResult node. The minio-py SDK treats this as XML parsing issue instead of raising an error indicating bad credentials.
Raise InvalidArgumentError when credentials are missing.
> Fix parsing failure for list_buckets with s3 endpoint

- minio/api.py
- minio/helpers.py
- tests/unit/minio_test.py
Additionally also support extracting region from the endpoint, this
technique is an optimization avoids GetBucketLocation() request
and makes it more performant.
Fixes #570
> Do not fail input checks for endpoints with .amazonaws.com as prefix

- minio/policy.py
dict.iteritems() is not supported in python 3 but we can safely use
dict.items() which provides a _view_ of dict elements.
Fixes #585
> Fix: Use dict.items() instead of dict.iteritems()

- minio/api.py
- minio/xml_marshal.py
- tests/unit/generate_xml_test.py
S3 spec requires a list of parts ordered by part numbers in complete
multipart call. dict.keys() was used and it returns an ordered list,
however Python doesn't garantuee that all the times. This PR will
enforce ordering list as it is expected.
Fixes #590
> fix: Order complete multipart list

- docs/API.md
- minio/__init__.py
- minio/api.py
Minio constructor has been modified to take a custom http client
from the user.
This prevents the constructor from having too many options.
The next version has been bumped to 3.0.0, since this change
breaks backward compatibility.
Fixes #588
> Allow users to use custom http client in the constructor

- minio/api.py
- minio/post_policy.py
- Add PostPolicy.append_policy for easy-accessing
- Keep post policy untouched while applying to Minio.presigned_post_policy
> add easy-access methods to PostPolicy

- minio/api.py
Since we do not have resuming support, we should
simply cleanup failed transfers.
> Cleanup incomplete upload upon error

- README_zh_CN.md
- docs/zh_CN/API.md
- docs/zh_CN/CONTRIBUTING.md
translate minio-py docs to Chinese.
> translate minio-py docs to Chinese.

- tests/functional/tests.py
sys.exit allows us to return non-zero exit status.
Fixes https://github.com/minio/mint/issues/246
> Use sys.exit instead of exit from site packages

- minio/helpers.py
- tests/unit/optimal_part_test.py
```
In [4]: optimal_part_info(549755813)
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-4-9348e40232c0> in <module>()
----> 1 optimal_part_info(549755813)
/data/apps/ecoboost-backend/ecoboost/eggs/minio-2.2.6-py2.7.egg/minio/helpers.py in optimal_part_info(length)
592                        * MIN_PART_SIZE)
593     # Total parts count.
--> 594     total_parts_count = int(math.ceil(length/part_size_float))
595     # Part size.
596     part_size = int(part_size_float)
ZeroDivisionError: integer division or modulo by zero
```
Uploaded failed when length larger than 5MB put_object.
env:
python version: 2.7.5
minio version: 2.2.6
> fix calculate optimal part size bug

- minio/api.py
- tests/functional/tests.py
> Adds missing tests and fixes tests with problems

- tests/functional/tests.py
Since '0' prefix was chosen it could happen such
that when listing the exact prefix match '0' due
to randomness of uuid we might have > 1 match,
this would lead to tests to fail sporadically.
This PR fixes this behavior by choosing a fixed
prefix and keeping UUID as a variable part of the
object name.
> fix test_list_objects_with_prefix bug when listing

- tests/functional/tests.py
> Fixes 2 tests failing for gateway azure

- minio/api.py
- tests/functional/tests.py
> Fixed test_thread_safe azure gateway failure

- minio/api.py
> Override all other regions if region is set

- minio/api.py
- setup.py
The `strptime()` function reads certain directives according to the locale configured in the environment, so the parsing fails in non-English locales, as the `Last Modified` date is always in English.
This commit imports `dateutil`, which parses the date without using `strptime`, and can correctly process English dates in any locale.
Fixes #632
> Fix date parsing

- minio/thread_pool.py
> Change ThreadPool and Worker class in thread_pool.py

- minio/api.py
minio-py loads a custom, or a set of custom certificates if SSL_CERT_FILE
is specified. Otherwise, certifi will still be used.
> Add SSL_CERT_FILE env. var. to specify custom CA certificate

- minio/api.py
The example was using a reference to `size` instead of `st_size`
> Fix put_object documentation example

- minio/api.py
- minio/helpers.py
Allows the connection pools to save 10 connections.
References:
- https://urllib3.readthedocs.io/en/1.4/pools.html#urllib3.connectionpool.HTTPConnectionPool
> Increase urllib3 connection pool size

- minio/helpers.py
Hi I see you set two url schemes here: https://github.com/minio/minio-py/blob/3b6e49c0e3a4a05640865065637033bfc5f9166d/minio/helpers.py#L240
But from `is_virtual_host` only in amazon s3 returns True. I think the first url scheme is the most common one. And [Aliyun OSS ](https://help.aliyun.com/document_detail/31978.html?spm=a2c4g.11186623.6.897.d0LvWt) only support the first url scheme.
Hope this can be merged ASAP.
> support aliyun OSS api

- docs/API.md
- minio/api.py
- minio/signer.py
This allows the request date used for presigning the request to be
configurable.
I want to make the request date configurable because I want to specify a custom
request date that is not datetime.utcnow(). For example, I want to make the
presign link to stay unchanged for a certain time period, which makes browser
caching easier.
I understand that this might not be what you guys want but I am going to try
my luck anyway :)
PS: `minio-js` has support for custom request date too, but that parameter is not exposed in exported function.
> Support for specifying custom presign request date

- minio/api.py
- minio/helpers.py
- tests/functional/tests.py
- tests/unit/header_value_test.py
Fixes #655 
Append x-amz-meta- prefix for user defined meta data if not already prefixed.
> api:put_object not saving user metadata without x-amz-meta- prefix 

- minio/api.py
use json.decoder.JSONDecodeError instead of SyntaxError
ref #652
> fix listen_bucket_notification

- minio/api.py
The server streams an empty string (" ") until an action hits the bucket, 
In this case `JSONEncodeError` exception is thrown for every `json.loads(" ")` , So the loop continues here and polls the request for every catch .
> Avoiding continuous polling in listen_bucket_notification 

- minio/xml_marshal.py
- tests/unit/set_bucket_notification_test.py
```python 
....
notification = {
'QueueConfigurations': [
{
'Id': '1',
'Arn': 'arn:minio:sqs::1:amqp',
'Events': ['s3:ObjectRemoved:*', 's3:ObjectCreated:*'],
'Filter': {
'Key': {
'FilterRules': [
{
'Name': 'prefix',
'Value': 'foo'
},
{
'Name': 'suffix',
'Value': 'bar'
}
]
}
}
}
]    
}
client.set_bucket_notification('api', notification)
```
before change:
```xml
<NotificationConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
<QueueConfiguration>
<Id>1</Id>
<Queue>arn:minio:sqs::1:amqp</Queue>
<Event>s3:ObjectRemoved:*</Event>
<Event>s3:ObjectCreated:*</Event>
</QueueConfiguration>
</NotificationConfiguration>
```
```sh
mc events list local/api
arn:minio:sqs::1:amqp   s3:ObjectRemoved:*,s3:ObjectCreated:*   Filter:
```
after change:
```xml
<NotificationConfiguration …
```
> fix set_bucket_notification filter

- minio/parsers.py
I believe it should be `InitiateMultipartUploadResult`
https://github.com/minio/minio/blob/3dc13323e51dc7038232f5f02f55b37b388c59c2/cmd/api-response.go#L228-L234
> Fix parse_new_multipart_upload

- minio/api.py
- minio/helpers.py
Fixes #681
Ensure that policy is always of type string when passed into set_bucket_policy api.
> adds support for string policy

- tests/functional/tests.py
c798b8c8322dda3cc710ce4c62061bcfc3132718 broke our functional
tests for non TLS server setups. This PR fixes this by
skipping encryption tests on non-TLS servers.
Fixes #691
> Fix broken tests with ENABLE_HTTPS=0

- minio/parsers.py
is_dir for listobjects was always set to `False` by default
So, it should be handled properly by decisions on the object_name , 
ie, to consider it as a dir if the name has "/" suffixed.
Fixes #695
> minio-py should honour `is_dir` in listobjects correctly

- minio/api.py
Encryption headers are not required during the PUT object part API call when creating an object using SSE-S3 and SSE-KMS encryption options. AWS S3 fails if these headers are set in this scenario.
Fix is same as minio/minio-go#1026
> Set Encryption headers only for SSE-C in multipart uploads

- tests/functional/tests.py
Currently, some tests fail if they are ran against a Minio
server loaded with a self signed certificate. The reason is that
some tests initialize a new http client without taking care of
SSL_CERT_FILE env variable.
> tests: Load CA cert from SSL_CERT_FILE if found

- minio/api.py
- minio/thread_pool.py
The multipart upload was reading all parts and putting them
in memory before calling for thread manager to upload parts
in parallel.
This commit changes the behavior to read a part only when a
worker becomes ready to upload.
fixes #626
> multipart: Avoid reading all parts at once before upload

- tests/functional/tests.py
This PR fixes the following functional test cases which were failing on s3
- test_put_object
- test_stat_object
Taking into account that, metadata can be case-insensitive, the metadata is normalized for test cases so that it could work for both s3 and minio. `Minio` responds with canonicalized metadata, but s3 does not.
Fixes #709
> Fix for the failing functional test cases for s3

- .travis.yml
- appveyor.yml
- setup.py
nose is a testing framework, however it is currently required to build Minio package.
This commit will disable this requirement.
Fixes #643
> Allow building minio without nose package

- tests/functional/tests.py
AWS S3 does not have a consistent behavior while putting a bucket twice,
besides, we want to make all tests successful at the same time for AWS,
Minio server and gateway S3.
This PR will remove bucket recreation test to reduce complexity.
Fixes #708
> tests: Remove recreate bucket test

- minio/thread_pool.py
put_object() prepares parts much more faster than uploading them,
the thing which leads to load all the data, such as a local file, in
the memory, which by itself can lead to a OOM.
This PR will allow only `num_threads` parallel task preparation of
parts data before multipart uploading them.
Fixes #704
> put_object: Limit tasks queue size to avoid reading the whole data

- minio/api.py
make_bucket() uses new bucket location to sign make bucket requests,
however region should be used instead, and 'us-east-1' if no region
is specified.
Fixes #712
> make_bucket: Use correct region when signing requests

- minio/api.py
`listen_bucket_notification` fails when receiving event in Python3
```
app_1              | Traceback (most recent call last):
app_1              |   File "/opt/project/app.py", line 70, in <module>
app_1              |     listen_on_new_files(mc, BUCKET_NAME, INPUT_PREFIX)
app_1              |   File "/opt/project/minio_utils/events.py", line 12, in listen_on_new_files
app_1              |     next(events_it)
app_1              |   File "/usr/local/lib/python3.5/site-packages/minio/api.py", line 515, in listen_bucket_notification
app_1              |     event = json.loads(line)
app_1              |   File "/usr/local/lib/python3.5/json/__init__.py", line 312, in loads
app_1              |     s.__class__.__name__))
app_1              | TypeError: the JSON object must be str, not 'bytes' …
```
> Convert bytes to str before parsing json in listen_bucket_notification

- tests/functional/tests.py
If copy object call is made with the option of replacing metadata,
and content type is not set, then the default content type can be either
binary/octet-stream or application/octet-stream.
Test should treat both as same.
Fixes https://github.com/minio/minio/issues/7238
> test: Content type by default can also be binary/octet-stream

- README.md
Full Examples: Bucket policy Operations is repeated twice
> Remove redundant text

- minio/helpers.py
- tests/unit/optimal_part_test.py
Use optimal part size determined by SDK only when client did not configure a part size.
Currently, the code still reverts to using optimal part size even though user configured a part size in the put_object call
> use optimal part size only when client did not configure part size

- minio/api.py
- tests/functional/tests.py
This is not a fix but debug code to add the following information to the `log_output` list to help diagnose the sporadic problem, explained in Issue #755.
```
log_output.args['presigned_get_object_url'] = presigned_get_object_url
log_output.args['response.status'] = response.status
log_output.args['response.reason'] = response.reason
log_output.args['response.headers'] = json.dumps(response.headers.__dict__)
log_output.args['response._body'] = response._body.decode('utf-8')
```
The suspicion is that the client and server times are not in sync and hence we sometimes see the problem when the expiration time is either comes earlier or later than expected.
> Adds debug code to diagnose Issue#755

- appveyor.yml
- minio/helpers.py
- tests/unit/get_s3_endpoint_test.py
For eg, `minio_server` should be treated as valid hostnames.
Fixes #760
> Validate underscores in host names successfully

- minio/helpers.py
- setup.py
Pass 'é' or other non us-ascii character as a metadata value shows
a signature mismatch error. The reason is that S3 server ignores
those characters in headers since only US-ASCII characters are
supported in HTTP headers.
This commit shows an exception so users can understand better
what's going on.
Fixes #764
> Better error msg if metadata contains a non us-ascii character

- docs/API.md
- examples/select_object_content.py
- minio/__init__.py
- minio/api.py
- minio/helpers.py
- minio/select_object_options.py
- minio/select_object_reader.py
- minio/xml_marshal.py
- tests/functional/tests.py
- tests/unit/generate_xml_test.py
Selects and filters out data from stored object.
Client implementation for select feature
Closes #762
> Implement select feature

- docs/API.md
- minio/api.py
- tests/unit/list_objects_v2_test.py
When listing a bucket or a prefix which contains a lot of files,
it is not possible to pause/resume listing using list-objects-v2
API, adding start_after will help the developer listing from a
starting point without having to list everything again from the
beginning.
Fix #718
> list-objects-v2: Add start_after parameter

- minio/helpers.py
In Minio Server documentation there are such Supported Event Types:
s3:ObjectAccessed:Get
s3:ObjectAccessed:Head
Using minio-py I can't set this type of notification event, because when is_valid_bucket_notification_config(notifications) checks notifications there are no such events.
I added new events
NOTIFICATION_EVENTS = {
's3:ObjectAccessed:*',
's3:ObjectAccessed:Get',
's3:ObjectAccessed:Head',
...
}
> ObjectAccessed with Get and Head methods

- minio/parsers.py
Some non Amazon S3 implementations are not consistent about including fractional seconds in the timestamp. The change allows parsing of both `2019-07-10T14:23:39.231Z` and `2019-07-10T14:23:39Z`.
> Add support for ISO time with and without fractional seconds.

- minio/parsers.py
Minio sometimes responds with newlines before the XML declaration. The `data` variable holds something like this:
`b'\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r<?xml version="1.0" encoding="UTF-8"?>\n<CompleteMultipartUploadResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Location>https://minio-api.example.com/storage/data.csv.gz</Location><Bucket>storage</Bucket><Key>data.csv.gz</Key><ETag>7c913063d32676ebb4356e68db88db20-3</ETag></CompleteMultipartUploadResult>'`
`xml.etree` can't parse such response with error `InvalidXMLError: message: "CompleteMultipartUploadResult" XML is not parsable. Message: XML or text declaration not at start of entity: line 32, column 0`. The solution is to strip white-space …
> InvalidXMLError: message: "CompleteMultipartUploadResult" XML is not parsable

- minio/api.py
Improve error message.
current problem:
> Fix: Missing space between words in error message

- minio/signer.py
Supplying port 80 or 443 with host (ex. `storage.googleapis.com:443`) fails in v4 signing. Remove these default ports to prevent signature matching failure.
Similar issue:
https://github.com/aws/aws-cli/issues/2883
> Strip port 80/443 from host

- minio/error.py
- minio/parsers.py
https://github.com/minio/minio-py/issues/801
As discussed in given issue, some Python packages do not support `message` attribute in exceptions, so it is safer to use string representation of them instead.
Please review and merge. :-)
> FIX: AttributeError at error.message #801

- README.md
This PR addressed this issue https://github.com/minio/minio-py/issues/806 
I propose removing the else from the code sample. This is because, with that else statement there, the file will only be uploaded if the bucket does not exist.
> Edit example code.

- minio/api.py
- minio/signer.py
- tests/unit/sign_test.py
Ceph radosgw seems to include ~ in the upload ID when the client
initiates a new multipart upload.
minio-py was wrongly encoding ~ in the query part of the url.
This PR ensures that to decode %7E to ~ before signing the request.
Fixes https://github.com/minio/minio-py/issues/810
> signV4: Avoid encoding ~ when found in the query part of the url

- minio/__init__.py
Possibly, previous incomplete build has some files with the same name in the repository
causing builds to fail.
> Increment build number

- minio/api.py
- tests/unit/list_incomplete_uploads_test.py
- tests/unit/list_objects_test.py
- tests/unit/list_uploaded_parts_test.py
MinIO server supports now 10k elements in the list output,
there is no reason for client to limit itself let the
default set of keys be returned and limited by server
implementation
> Do not need to set max-keys, max-uploads and max-parts

- minio/helpers.py
Fixes #835 
In newer versions of Python, such as 3.7.6, the standard urlparse does not parse endpoint 'media:9004' as it is used to be.
```
Python 3.7.6 (default, Dec 20 2019, 22:50:33) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import urllib.parse
>>> urlsplit = urllib.parse.urlsplit
>>> urlsplit('media:9000')
SplitResult(scheme='media', netloc='', path='9000', query='', fragment='')
```
The new Python documentation states that we need to add '//' to enforce parsing media as a hostname, which is done in this PR.
> Fix detecting a valid endpoint with new Python versions

- minio/api.py
- minio/helpers.py
- minio/post_policy.py
- tests/unit/bucket_exist_test.py
- tests/unit/minio_test.py
- tests/unit/remove_bucket_test.py
- tests/unit/remove_object_test.py
- tests/unit/remove_objects_test.py
- tests/unit/stat_object_test.py
Fixes #838.
To fix this issue, the implementation difference between minio-go and minio-py is needed to be addressed. 
With the fix, just like in minio-go, dev-engineers are now able to call strict or looser bucket name validation depending on the api.
Strict validation is only used for `make_bucket` api, and looser bucket name validation is used for the rest.
The relaxation accomplished with the new approach is listed below:
- Capital letters of English alphabet
- underscore character, `_`
- colon character, `:`
Now, they are also valid characters.
> fix: relax bucket_name validation for existing buckets

- minio/api.py
- minio/helpers.py
This PR add support for Amazon S3 Transfer Acceleration.
Acceleration is enable by using `client.use_s3_accelerate(True)`. This function is a noop is the `endpoint_url` is not point to `s3.amazonaws.com`.
When presigned generators are called eg. `client.presigned_get_object` internally i am checking the following.
- if S3 Accelerate is enable using `self._enable_s3_accelerate`
- if the bucket has accelerate configured using `self.is_bucket_acclerate_configured`
If both the conditions are satisfied i switch the endpoint_url (pass to `get_target_url`) to `://s3-accelerate.amazonaws.com`
> Add support for Amazon S3 Transfer Acceleration for presigned urls

- examples/aws_credentials.py
- examples/chain_credentials.py
- minio/credentials/aws_iam.py
- tests/unit/iam_aws_test.py
Fixes issue #857 
As the issue explains, IamEc2MetaData attempts to access http response data and status using subscripts like the example shown below:
```
if res['status'] != 200:
return []
```
This throws an exception because the `'HTTPResponse' object is not subscriptable`.
> Fixes not subscriptable objects

- minio/compat.py
- minio/error.py
- minio/parsers.py
- minio/select/reader.py
> cElementTree has been deprecated since Python 3.3 and removed in Python 3.9

- MANIFEST.in
Fixes #865 
Added the missing `minio/credentials/*.sample` files into the tarball python package generation process.
I've also tested and checked the content of the generated tarball to make sure the missing files are included.
> Adds missing 'minio/credentials/*.sample' files

- MANIFEST.in
We first include all files needed to run the tests from a sdist.
Previously, I get 4 errors and 4 failures due to files not found by
tests.
We also prune files which do not seem needed when using the sdist
package.
The correctness of the update MANIFEST.in can be verify using
check-manifest.
> Update MANIFEST.in to generate a complete sdist

- minio/compat.py
- minio/helpers.py
- minio/parsers.py
- tests/unit/sign_test.py
Quote and unquote are the names of the urllib functions being wrapped, this PR is a minor refactor to use those names.
Motivation is to avoid confusion when needing to use the real `urlencode` function (cf [comment](https://github.com/minio/minio-py/pull/874#discussion_r405801164)).
> Rename urlencode and urldecode to quote and unquote

- minio/signer.py
- tests/unit/sign_test.py
Refactors `sign_v4` to take an optional `service` argument making it possible to sign for services other than `"s3"`, e.g. to allow the client to craft an `AssumeRole` request using the `"STS"` service.
*Note this PR extracts just the signature changes from PR #874*
> Allow signing requests for services other than s3 in sign v4

- examples/assume_role.py
- minio/compat.py
- minio/credentials/__init__.py
- minio/credentials/assume_role.py
- minio/credentials/aws_iam.py
- minio/credentials/credentials.py
- minio/credentials/parsers.py
- minio/error.py
- minio/helpers.py
- minio/parsers.py
- minio/signer.py
This PR adds a `assume_role` api to mino-py allowing users to generate temporary credentials using the `AssumeRole` STS API. It has to modify how signatures are generated to allow signing requests for other services e.g., `"sts"`.
I'm assuming the functional python API should be replaced - but let me know.
Further discussion original feature request in #871.
Server side API documentation:
- https://github.com/minio/minio/blob/master/docs/sts/assume-role.md
- https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html
> add support for AssumeRole provider

- minio/api.py
Hello Minio Team,
Talked with @harshavardhana and it seems the encoding is a bit off for the minio python sdk. It seems the value of the `x-amz-copy-source` does not need to encode the individual `/` characters in a provided path.
> change encoding of x-amz-copy-source in copy_object

- examples/assume_role.py
- minio/api.py
- minio/credentials/assume_role.py
- minio/credentials/credentials.py
- minio/credentials/parsers.py
- minio/parsers.py
Instead, have a callback with arguments (Merely a design fix)
> Avoid passing the client to the assume role provider

- minio/thread_pool.py
put_object() allocates more memory than what we would expect. The
reason is that workers upload parts while the main code allocates
memory for the new parts that are being read from the source stream.
A semaphore is used in add_task() to make this latter blocking. That
way, the main code won't hurry to allocate new memory space for the
new data of the source stream.
Fixes #929
> Less memory allocation with put_object()

- minio/credentials/providers.py
- tests/unit/credentials_test.py
Subtracts time delta from AWS IAM expiration time.
Tries to solve #934
> Removed iam time delta

- minio/api.py
- minio/definitions.py
- minio/parsers.py
- minio/xml_marshal.py
- tests/functional/tests.py
- tests/unit/list_objects_test.py
- tests/unit/list_objects_v2_test.py
Added support to below APIs
* enable_bucket_versioning()
* disable_bucket_versioning()
* fget_object()
* get_object()
* stat_object()
* remove_object()
* remove_objects()
* presigned_get_object()
* list_objects()
* list_objects_v2()
> Add object version-ID support

- docs/API.md
- Added empty string after the line 80 to avoid consideration of Python
code as part of citation block.
> Fixed small Markdown rendering issue

- examples/progress.py
But the imports in `examples/progress.py` were not updated -> import error. PR after fixing it in one of my projects after upgrading to 6.0.
> queue and queue_empty were removed from compat.py in minio-py 6.0

- MANIFEST.in
When the credential changes were merged, MANIFEST.in was not also
changed to make certain the new file paths were shipped in the build
sdist. Drop the minio/credentials line and add those globs to tests.
Fixes #961
> Ship missing credential files in MANIFEST.in

- minio/copy_conditions.py
`collections.abc` has been the preferred import since Python 3.3. The oldest version presently supported by minio is Python 3.4.
This fixes a `DeprecationWarning` raised in Python 3.8.
> Remove collections.abc fallback import

- setup.py
`future` was only required for Python 2, which is not supported by minio.
> Remove unnecessary requirement on "future"

- docs/API.md
- minio/__init__.py
- minio/api.py
- minio/definitions.py
- minio/parsers.py
- minio/xml_marshal.py
- tests/functional/tests.py
> Add {set,get}_bucket_versioning() APIs

- minio/api.py
- minio/credentials/providers.py
- minio/signer.py
Minio's Presigned URL didn't support an IAM role which requires a session token for a presigned URL.
I followed the code of the botocore.
https://github.com/boto/botocore/blob/30206ab9e9081c80fa68e8b2cb56296b09be6337/botocore/auth.py#L484-L492
This PR has includes the fix of #998 because it cannot test the function without it.
> Populate available session token in presigned_url()

- .github/workflows/pythonpackage-linux.yml
- .github/workflows/pythonpackage-windows.yml
- README.md
- setup.py
- Add python 3.9 to tested python versions
- Use  setup-python@v2 (v1 has bug, see https://github.com/actions/setup-python/issues/154)
- Update setup.py that the library supports python 3.9
> Add python 3.9 support in github workflow.

- minio/credentials/providers.py
Ensure duration in seconds is an integer. 
Closes #1080
> Convert timedelta.total_seconds() to integer in credential providers.

- minio/api.py
To resolve ResourceWarnings from requests lib about unclosed SSLSockets - see psf/requests#1882.
It happens on pytest==6.2
pytest.PytestUnraisableExceptionWarning: Exception ignored in: <ssl.SSLSocket fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6>
ResourceWarning: unclosed <ssl.SSLSocket fd=7, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('172.28.0.10', 44592),>
> Added destructor to clear urllib3.PoolManager

- minio/credentials/providers.py
Keep both the old format and the new format key to support older and the current mc config files
> Add new config format support in MinioClientConfigProvider

- minio/api.py
> make_bucket: use region passed via constructor

- minio/datatypes.py
Hello there,
I added these changes for multiple reasons,
* First of all, when I'm dealing with buckets they lack string representation which is handly some use cases:
```python
In [4]: client.list_buckets()
Out[4]: 
[<minio.datatypes.Bucket at 0x7f15f097dc70>,
<minio.datatypes.Bucket at 0x7f15eaae73d0>]
In [5]: # It could have been something like this:
Out[5]: [Bucket('a'), Bucket('b')]
In [6]: for b in client.list_buckets():
...:     print(b)
...: 
<minio.datatypes.Bucket object at 0x7f15eb4c4cd0>
<minio.datatypes.Bucket object at 0x7f15eaedda00>
In [7]: for b in client.list_buckets():
...:     print(b)
...: 
a
b
```
But more importantly, I wanted to check if a specific bucket exists inside a list of buckets, I know I can use `bucket_exists` method, but it's good to have an equality …
> Bucket: add string representation and equality method

- minio/minioadmin.py
`json.loads(line)` would throw an error if line is empty (e.g. `line == b''`).
To fix it, simply check if line is truthy (i.e. not empty).
Also, since `proc.stdout` is of type `bytes` the argument passed to
`proc.stdout.split` was changed to `b"\n"`.
> Handle empty stdout properly in MinioAdmin

- minio/minioadmin.py
`MinioAdmin` now accepts another argument `env` which will be passed to the
underlying `subprocess.run` call. It can be used to set custom environments for
the `mc admin` subprocess, e.g. you could set `MC_HOST_<alias>` per `MinioAdmin`
instance.
> Add environment variables support to MinioAdmin

- minio/helpers.py
- tests/functional/tests.py
Bonus: also stringify the `key` for
additional metadata, otherwise key's with
numeric names might fail with key ValueError.
> fix: pylint build issues in minio-py

- docs/API.md
I noticed in [reference docs](https://docs.min.io/docs/python-client-api-reference.html) I couldn't jump to `get_presigned_url` method by clicking on it because it was missing an anchor tag
> docs: add anchor for `get_presigned_url` method in API docs

- minio/datatypes.py
Fixes #1125
Signed-off-by: Bala.FA <bala.gluster@gmail.com>
> EventIterable: use looping instead of tail recursion in __next__()

- minio/credentials/providers.py
- minio/signer.py
additionally this PR allows content-type and
content-length to be part of signed headers as
this is allowed in signature v4.
> fix: canonical request path if empty choose '/'

- minio/credentials/providers.py
AWSConfigProvider and MinioClientConfigProvider look for config files under home directory, which is retrieved as `os.environ.get("HOME")`. However, under Windows this env var does not exists and the `os.path.join` raises a TypeError. Fixed by getting `os.environ.get("UserProfile")` or `str(Path.home())` as a last resort.
> fix finding user's home directory in AWSConfigProvider/MinioClientConfigProvider 

- minio/credentials/providers.py
- tests/unit/credentials_test.py
Some providers, eg, EnvAWSProvider and EnvMinioProvider, creates the Credential object during __init__. However, if a key is None, a ValueError is raised. Therefore, when these providers are used within a ChainedProvider, the exception is raised before actually retrieving the credentials.
This bug is highlighted by the new test ChainedProviderTest.test_chain_retrieve_second, which fails without the proposed fix.
> fix EnvAWSProvider/EnvMinioProvider to fetch access/secret keys and session token always from os.environ

- minio/minioadmin.py
Hello, I have noticed that the `minio admin policy unset` method was missing from the MinioAdmin class!
> Add policy unset method to minio admin

- examples/minio_with_certificate_identity_provider.py
- minio/credentials/providers.py
> Add AssumeRoleWithCertificate credential provider.

- Makefile
- setup.py
- tests/unit/bucket_exist_test.py
- tests/unit/credentials_test.py
- tests/unit/get_bucket_policy_test.py
- tests/unit/get_object_test.py
- tests/unit/list_buckets_test.py
- tests/unit/list_objects_test.py
- tests/unit/list_objects_v1_test.py
- tests/unit/make_bucket_test.py
- tests/unit/presigned_get_object_test.py
- tests/unit/remove_bucket_test.py
- tests/unit/remove_object_test.py
- tests/unit/remove_objects_test.py
- tests/unit/stat_object_test.py
mock is not required to run the testsuite, so use built in unittest.mock.
> use unittest.mock instead of mock

- minio/datatypes.py
using response.stream() doesn't work with nginx due to unknown
reasons, mostly perhaps how nginx writes the body of the
response. Instead use response.readline() instead allows for
reading the right amount of content() needed for events.
> fix: listen bucket event response should use response.readline()

- minio/helpers.py
- minio/sse.py
in non-FIPS environments, the flag would be ignored.
will fix #789
> allow hashlib.md5() calls to work with FIPS kernels

- minio/select.py
- tests/functional/tests.py
When the specified number of bytes was less than the payload size, the rest of the payload was discarded. I fixed the method and adjusted the test to trigger this behavior.
> select: yield available payload fully by requested num_bytes

- setup.py
I suggest to change the license string in the package information to an [SPDX parsable license expression](https://spdx.org/licenses/).
This makes it easier for downstream users to get the license information directly from the package metadata.
> Use Apache license SPDX identifier

- minio/api.py
- minio/datatypes.py
> fix usage of deprecated urllib3.Response.getheaders()

- .github/workflows/pythonpackage-linux.yml
- docs/API.md
- examples/remove_objects.py
- minio/api.py
- minio/commonconfig.py
- minio/helpers.py
- minio/select.py
- minio/sseconfig.py
- pylintrc
- tests/functional/tests.py
Found via `codespell -S .mypy_cache`
> Fix typos and add codespell GitHub Action

- minio/api.py
Add code to expose the fetch_owner parameter in `_list_objects` in `list_objects`.
> Expose fetch-owner in the api for list_object

- .github/workflows/pythonpackage-linux.yml
- .github/workflows/pythonpackage-macos.yml
- .github/workflows/pythonpackage-windows.yml
- minio/api.py
- minio/datatypes.py
- setup.py
The core dependencies used by this package seem to be running with Python version 3.11 (more checks might be due).
This is an attempt to bump the test matrix and fix a warning regarding the deprecation of `HTTPResponse.getheader()`
Here the warning I was getting:  
```
DeprecationWarning: HTTPResponse.getheader() is deprecated and will be removed in urllib3 v2.1.0. Instead use HTTResponse.headers.get(name, default).
```
Here my environment:
**MacOS 13.0.1** (M1 chip),
Anaconda **Python version 3.11**
and here the result of **pip list**
```
Package           Version
----------------- ---------
astroid           2.12.13
attrs             22.1.0
autopep8          2.0.1
certifi           2022.12.7
dill              0.3.6
iniconfig         1.1.1
isort             5.11.3
lazy-object-proxy 1.8.0 …
```
> Add python 3.11 support

- README.md
There were two references to the obsolete release branch, change them to point to master
> update release references to master in README.md

- minio/api.py
- tests/functional/tests.py
There is a bug in upload_snowball_objects when it is called with "staging_filename" parameter. The variable "length" passed to fput_object is not defined in this case.
> Fix upload snowball objects with staging file

- minio/api.py
`fget_object` got exception when download temporary file in a non-exists directory.
```
Traceback (most recent call last):
File "/home/laisky/repo/laisky/ramjet/ramjet/tasks/gptchat/utils.py", line 98, in wrapper
return await func(self, *args, **kwargs)
File "/home/laisky/repo/laisky/ramjet/ramjet/tasks/gptchat/utils.py", line 72, in wrapper
return await func(self, userinfo, *args, **kwargs)
File "/home/laisky/repo/laisky/ramjet/ramjet/tasks/gptchat/router.py", line 798, in post
return await ioloop.run_in_executor(
File "/home/laisky/.pyenv/versions/3.10.0/lib/python3.10/concurrent/futures/thread.py", line 52, in run
result = self.fn(*self.args, **self.kwargs)
File "/home/laisky/repo/laisky/ramjet/ramjet/tasks/gptchat/router.py", line 900, in build_chatbot
self._build_user_chatbot(
File …
```
> prepare temporary directory when `fget_object`

- minio/api.py
`Minio.remove_objects` expects a list of `DeleteObject`s, but the documentation uses a `map`. If a `map` is passed to `Minio.remove_objects`, it will silently fail, and the objects will not be deleted. This PR corrects the documentation to pass a `list` instead of a `map` to `Minio.remove_objects`.
> fix remove_objects() example to convert map to list of map

- minio/crypto.py
- minio/minioadmin.py
- tests/unit/crypto_test.py
- tests/unit/minio_mocks.py
> Remove 16KiB limit in MinioAdmin crypto functions

- NOTICE
- README.md
Improve the Python Quickstart:
- Add a minimal client example
- Clarify the steps to run the file uploader example.
- Update text and formatting to more closely match the MinIO docs.
Since this repo doesn't use the Docs staging server, this direct link in GitHub is an easier way to see an overview of changes than reading the diff:
https://github.com/feorlen/minio-py/blob/readme-quickstart-update/README.md
This update roughly follows the structure of the `minio-go` [README](https://github.com/minio/minio-go/blob/master/README.md).
Corresponding docs issue: https://github.com/minio/docs/issues/1042
> Update the Python Quickstart README

- setup.py
From #1378 minio 7.2.1 requires urllib3>=2.0 because it uses `urllib3.response.BaseHTTPResponse `
```
➜  minio-py git:(master) pip install git+https://github.com/ydc-0/minio-py.git@master
...
Installing collected packages: urllib3
Attempting uninstall: urllib3
Found existing installation: urllib3 1.26.18
Uninstalling urllib3-1.26.18:
Successfully uninstalled urllib3-1.26.18
Successfully installed urllib3-2.1.0
```
> fix install_requires urllib3

- minio/__init__.py
Mypy with strict mode enabled gives the following error on version [7.2.2](https://github.com/minio/minio-py/tree/7.2.2):
```
error: Module "minio" does not explicitly export attribute "Minio"  [attr-defined]
```
The error is caused by rule [--no-implicit-reexport](https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport). There are two ways how to fix it: either define `__all__` in `__init__.py` or use import aliases so that other modules can import it. In this PR I added aliases for all imports in `__init__.py`.
> Add import aliases to make mypy happy

- docs/API.md
Adds `cert_check` kwarg to the `Minio` class docs
> Update docs for cert_check flag

- minio/api.py
The `delete_object_list` argument in `minio.api.remove_objects` was annotated as `Iterator[DeleteObject]`. This means that mypy would complain if client code passes a list of `DeleteObject`-s to remove_objects.
But in practice passing in a list works: the `delete_objects` function converts the list to an iterator using `itertools.chain`.
I changed the type annotation to `Iterable[DeleteObject]`. This way, mypy is happy if we pass an iterator, and when we pass a list.
(And same thing in upload_snowball_objects)
Here's a small isolated testcase demonstrating the problem:
```python
from __future__ import annotations
from collections.abc import Iterable
from typing import Iterator
def foo(data: Iterator[int]):
pass
a = [1, 2, 3, 4]
foo(a)
foo(iter(a))
```
Running mypy on it results in:
``` …
```
> fix typing in remove_objects/upload_snowball_objects APIs

- minio/crypto.py
> fix DecryptReader to handle stream data correctly

- minio/versioningconfig.py
- tests/unit/versioningconfig_test.py
Add ExcludedPrefixes option to VerionningConfig.
Mimicks the behaviour of the minio cli `mc` [link](https://min.io/docs/minio/linux/administration/object-management/object-versioning.html#id9)
Started from issue #1401
> Add ExcludedPrefixes option to VersioningConfig

- minio/api.py
> fix range calculation in compose_object API

- setup.py
#1413 removed Python 3.7 from a list of supported Python versions. But `minio-py` still can be installed on Python 3.7.
If some next release introduces any change not compatible with 3.7 (e.g. walrus operator or some new typing annotations), users with this Python version should explicitly add an upper limit for package version, to avoid breaking changes.
Added [python_requires](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#python-requirement) to `setup.py` which prevents installing this package on Python below 3.8.
> Don't install package on Python below 3.8

- minio/credentials/providers.py
- tests/unit/credentials_test.py
This PR updates the `IamAwsProvider` to use IMDSv2, which is [automatically enabled](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/configuring-IMDS-new-instances.html) for all AWS EC2 / ECS instances.
I'm using this on an internal project successfully since ~a week, so contributing it back upstream.
Closes https://github.com/minio/minio-py/issues/1411.
> update IamAwsProvider as per minio-go implementation

- examples/get_object.py
- minio/api.py
I used `get_object` as example shown:
```py
try:
response = client.get_object("my-bucket", "my-object")
finally:
response.close()
response.release_conn()
```
But I got the `UnboundLocalError` when encountered exception in `get_object`. 
```
UnboundLocalError: local variable 'response' referenced before assignment
```
However, the [fget_object](https://github.com/minio/minio-py/blob/b7da8a891466755b3883612d230aa9580781ed6d/minio/api.py#L1131-L1159) api has handled this situation, so I think `get_object` should do so.
```diff
+response = None
try:
response = client.get_object("my-bucket", "my-object")
except Exception:
finally:
+    if response:
response.close()
response.release_conn()
```
> docs(example): Avoid `UnboundLocalError` for get_object when exception

- minio/api.py
- minio/commonconfig.py
> fix SnowballObject typing

- minio/credentials/providers.py
> WebIdentityClientGrantsProvider: use 'id_token' as fallback to 'access_token'

- minio/helpers.py
Hello. 
Found that minio encounters deadlocks when uploading large files in certain cases. Further investigation reveals that the thread pool can experience deadlocks under specific conditions. 
The minimal reproduction code is as follows: 
```python
from threading import BoundedSemaphore, Thread
from queue import Queue
import time
class Worker(Thread):
def __init__(self, tasks_queue, results_queue, exceptions_queue):
Thread.__init__(self)
self.tasks_queue = tasks_queue
self.results_queue = results_queue
self.exceptions_queue = exceptions_queue
self.daemon = True
self.start()
def run(self):
while True:
task = self.tasks_queue.get()
if not task:
self.tasks_queue.task_done()
break
if self.exceptions_queue.empty():
func, args, kargs, cleanup_func = task
try:
result = func(*args, **kargs) …
```
> fix calling cleanup function in Worker.run() to avoid race condition

- docs/API.md
- minio/api.py
> list_objects: add extra headers and extra query parameters

- minio/versioningconfig.py
- tests/functional/tests.py
Fix parsing of ExlucdedPrefix in set/get bucket versioning API.
ExcludedPrefixes includes Prefix tag and not ExcludedPrefix as stated in
the S3 spec.
> Fix ExcludedPrefixes in set/get bucket versioning config

- minio/minioadmin.py
Account info admin command was missing in admin client and needed to get bucket information (just like what we have in console)
> Add account_info Admin API

- minio/minioadmin.py
It would be nice to be able to add/update IAM/service account policies through Python dict objects as well as what's currently available through JSON files.
This PR tries to accomplish this.
Feedback/questions welcome.
Depends on https://github.com/minio/minio-py/pull/1483
> MinioAdmin: allow specifying policies as dict besides file

- minio/credentials/providers.py
> Credentials: redact password in URL

- minio/sse.py
It is confusing to say "SSE-C keys need to be 256 bit base64 encoded" when the `key` argument must not be base64 encoded, this is handled by the function internally
> cleanup: SSE-C keys fix a misleading error message

- setup.py
`py.typed` is not included in packages. I fixed setting.py.
> feat: add py.typed in setup.py
